routes/web.php
<?php

Route::prefix('backstage')->middleware('setActiveCampaign')->group(function () {
    // Account activation
    Route::get('activate/{ott}', 'Auth\ActivateAccountController@index')->name('backstage.activate.show');
    Route::put('activate/{ott}', 'Auth\ActivateAccountController@update')->name('backstage.activate.update');

    // Authentication
    Auth::routes([
        'register' => false,
    ]);

    Route::namespace('Backstage')->name('backstage.')->middleware('auth')->group(function () {
        // Campaigns
        Route::get('campaigns/{campaign}/use', 'CampaignsController@use')->name('campaigns.use');
        Route::resource('campaigns', 'CampaignsController');

        // Dashboard
        Route::resource('/', 'DashboardController');
        Route::resource('dashboard', 'DashboardController');

        // Users
        Route::resource('users', 'UsersController');

        Route::group(['middleware' => ['redirectIfNoActiveCampaign']], function () {
            Route::resource('prizes', 'PrizesController');
            Route::resource('games', 'GamesController');
        });
    });
});

Route::get('{campaign:slug}', 'FrontendController@loadCampaign');
Route::get('/', 'FrontendController@placeholder');

app/Http/Controllers/Backstage/BackstageController.php
<?php

namespace App\Http\Controllers\Backstage;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class BackstageController extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Backstage/CampaignsController.php
<?php

namespace App\Http\Controllers\Backstage;

use Carbon\Carbon;
use App\Models\Campaign;
use Carbon\CarbonPeriod;
use App\Http\Requests\Backstage\Campaigns\StoreRequest;
use App\Http\Requests\Backstage\Campaigns\UpdateRequest;

class CampaignsController extends BackstageController
{


    public function __construct()
    {
        $this->authorizeResource(Campaign::class, 'campaign');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('backstage.campaigns.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backstage.campaigns.create', [
            'campaign' => new Campaign(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         // Validation
         $data = $this->validate(request(), [
            'name' => 'required|unique:campaigns|max:255',
            'timezone' => 'required',
            'start_date' => 'required|date_format:Y-m-d H:i:s',
            'end_date' => 'required|date_format:Y-m-d H:i:s',
        ]);

        //parse dates from campaign's timezone
        $startDate = Carbon::createFromFormat('Y-m-d H:i:s', $data['start_date'], $data['timezone'])
            ->setTimezone('UTC');
        $data['start_date'] = $startDate;

        $startDate = Carbon::createFromFormat('Y-m-d H:i:s', $data['end_date'], $data['timezone'])
            ->setTimezone('UTC');
        $data['end_date'] = $startDate;

        // Create the campaign
        $campaign = Campaign::create($data);

        // Set message
        session()->flash('success', 'The campaign has been created!');

        // Redirect
        return redirect()->route('backstage.campaigns.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Campaign $campaign)
    {
        return view('backstage.campaigns.edit', compact('campaign'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Campaign $campaign)
    {
        // Validation
        $data = $this->validate(request(), [
            'name' => 'required|max:255|unique:campaigns,name,'.$campaign->id,
            'timezone' => 'required',
            'start_date' => 'required|date_format:Y-m-d H:i:s',
            'end_date' => 'required|date_format:Y-m-d H:i:s',
        ]);

        //parse dates from campaign's timezone
        $startDate = Carbon::createFromFormat('Y-m-d H:i:s', $data['start_date'], $data['timezone'])->setTimezone('UTC');
        $data['start_date'] = $startDate;

        $startDate = Carbon::createFromFormat('Y-m-d H:i:s', $data['end_date'], $data['timezone'])->setTimezone('UTC');
        $data['end_date'] = $startDate;

        // Update the campaigns data
        $campaign->update($data);

        // Redirect
        session()->flash('success', 'The campaign details have been saved!');

        return redirect()->route('campaigns.edit', $campaign->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Campaign $campaign)
    {
        $campaign->forceDelete();

        if (request()->ajax()) {
            return response()->json(['status' => 'success']);
        }

        session()->flash('success', 'The campaign has been removed!');

        return redirect(route('backstage.campaigns.index'));
    }

    public function use(Campaign $campaign)
    {
        session()->put('activeCampaign', $campaign->id);

        return redirect()->route('backstage.campaigns.index');
    }
}

app/Http/Controllers/Backstage/DashboardController.php
<?php

namespace App\Http\Controllers\Backstage;

    use App\Http\Controllers\Controller;

    class DashboardController extends Controller
    {
        public function index()
        {
            return view('backstage.dashboard.index');
        }
    }

app/Http/Controllers/Backstage/GamesController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Requests\Backstage\Campaigns\StoreRequest;
use App\Http\Requests\Backstage\Campaigns\UpdateRequest;
use App\Models\Artwork;
use App\Models\Campaign;
use App\Models\Game;
use App\Models\Prize;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

class GamesController extends BackstageController
{
    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('backstage.games.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update()
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Campaign $campaign)
    {
        //
    }


}

app/Http/Controllers/Backstage/PrizesController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backstage\Prizes\StoreRequest;
use App\Http\Requests\Backstage\Prizes\UpdateRequest;
use App\Models\Prize;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;

class PrizesController extends Controller
{
    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backstage.prizes.index');
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {

        $prize = new Prize();
        // Return the view
        return view('backstage.prizes.create', compact('prize'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreRequest $request)
    {
          // Validation
          $data = $this->validate(request(), [
            'title' => 'required|max:255',
            'weight' => 'required|numeric|between:0.01,99.99',
            'startDate' => 'required|date_format:Y-m-d H:i:s',
            'endDate' => 'required|date_format:Y-m-d H:i:s',
            'description' => 'sometimes',
            'level' => 'required|in:low,med,high',
        ]);

        // Add the campaign id to the data array.
        $data['campaign_id'] = session('currentCampaign');

        // Create the prize
        $prize = Prize::create($data);

        // Redirect with success message
        session()->flash('success', 'The prize has been created!');

        return redirect('/backstage/prizes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Prize $prize)
    {
        return view('backstage.prizes.show', [
            'prize' => $prize,

        ]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Prize $prize)
    {

       // Check if the user is authorized.
       $this->authorize('update', $prize);

       // Return the view
       return view('backstage.prizes.edit', compact('prize'));
    }

    /**
     * Update the specified resource in storage.
     * @param UpdateRequest $request
     * @param Prize $prize
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, Prize $prize)
    {
         // Check if the user is authorized.
         $this->authorize($prize);

         // Validation
         $data = $this->validate(request(), [
             'title' => 'required|max:255',
             'weight' => 'required|numeric|between:0.01,99.99',
             'startDate' => 'required|date_format:Y-m-d H:i:s',
             'endDate' => 'required|date_format:Y-m-d H:i:s',
             'description' => 'sometimes',
             'level' => 'required|in:low,med,high',
         ]);

         // Add the currentPeriod to the data array.
         $data['campaign_id'] = session('currentCampaign');

         // Create the prize
         $prize->update($data);

         // Redirect with success message
         session()->flash('success', 'The prize has been updated!');

         return redirect('/backstage/prizes/'.$prize->id.'/edit');
    }

    /**
     * Remove the specified resource from storage.
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Prize $prize)
    {
        $prize->forceDelete();

        if (request()->ajax()) {
            return response()->json(['status' => 'success']);
        }

        session()->flash('success', 'The prize has been removed!');

        return redirect(route('backstage.prizes.index'));
    }


}

app/Http/Controllers/Backstage/SymbolController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;

class SymbolController extends Controller
{
    //
}

app/Http/Controllers/Backstage/UsersController.php
<?php

namespace App\Http\Controllers\Backstage;

    use App\Models\User;
    use Illuminate\Support\Str;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use Illuminate\Support\Facades\Mail;
    use App\Mail\Backstage\Users\WelcomeMail;
    use App\Http\Requests\Backstage\Users\StoreRequest;
    use App\Http\Requests\Backstage\Users\UpdateRequest;

    class UsersController extends Controller
    {
        public function __construct()
        {
            $this->authorizeResource(User::class, 'user');
        }

        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            return view('backstage.users.index');
        }

        /**
         * Show the form for creating a new resource.
         * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
         */
        public function create()
        {
            return view('backstage.users.create', [
                'user' => new User(),
            ]);
        }

        /**
         * Store a newly created resource in storage.
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\RedirectResponse
         */
        public function store(StoreRequest $request)
        {
            // Setup the data
            $data = $request->validated();
            $password = Str::random(10);
            $data['password'] = bcrypt($password);

            // Create the user
            $user = User::create($data);

            // Setup a one time token
            $user->update([
                'ott' => encrypt($user->id),
            ]);

            // Send the welcome email
            Mail::to($user)->queue(new WelcomeMail($user));

            // Set message
            session()->flash('success', 'The user has been created!');

            // Redirect
            return redirect()->route('backstage.users.index');
        }

        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         * @param  int  $id
         * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
         */
        public function edit(User $user)
        {
            return view('backstage.users.edit', [
                'user' => $user,
            ]);
        }

        /**
         * Update the specified resource in storage.
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\RedirectResponse
         */
        public function update(UpdateRequest $request, User $user)
        {
            // Set base data
            $data = $request->validated();

            // Check if we have a new password
            if (isset($data['password'])) {
                if (auth()->user()->id !== $user->id) {
                    unset($data['password']);
                } else {
                    $data['password'] = bcrypt($data['password']);
                }
            }

            // Update the user
            $user->update($data);

            session()->flash('success', 'The user details have been saved!');

            return redirect()->route('backstage.users.edit', $user->id);
        }

        /**
         * Remove the specified resource from storage.
         * @param  int  $id
         * @return \Illuminate\Http\JsonResponse
         */
        public function destroy(User $user)
        {
            $user->forceDelete();

            if (request()->ajax()) {
                return response()->json(['status' => 'success']);
            }

            session()->flash('success', 'The user has been removed!');

            return redirect(route('backstage.users.index'));
        }
    }

app/Http/Livewire/Backstage/TableComponent.php
<?php

    namespace App\Http\Livewire\Backstage;

    use App\Models\User;
    use Livewire\Component;
    use Livewire\WithPagination;

    class TableComponent extends Component
    {
        use WithPagination;

        public $perPage = 10;

        public $search = '';

        public $sortAsc = true;

        public $hasSearch = true;

        protected $listeners = ['resourceDeleted'];

        public function sortBy($field)
        {
            if ($this->sortField === $field) {
                $this->sortAsc = ! $this->sortAsc;
            } else {
                $this->sortAsc = true;
            }

            $this->sortField = $field;
        }

        public function resourceDeleted()
        {
            // No need to do anything
            //we just reload the data
        }
    }

resources/views/backstage/prizes/create.blade.php
@extends('templates.backstage')

@section('tools')
    <a href="{{ route('backstage.prizes.index') }}" class="button-default">Prizes</a>
@endsection

@section('content')
    <div id="card" class="bg-white shadow-lg mx-auto rounded-b-lg">
        <div class="px-10 pt-4 pb-8">
            <h1>Add a new prize</h1>
            <form method="POST" action="{{ route('backstage.prizes.store') }}" enctype="multipart/form-data">
                @include('backstage.prizes.form')

            </form>
        </div>
    </div>
@endsection

resources/views/backstage/prizes/edit.blade.php
@extends('templates.backstage')

@section('tools')
    <a href="{{ route('backstage.prizes.index') }}" class="button-default">Prizes</a>
@endsection

@section('content')
    <div id="card" class="bg-white shadow-lg mx-auto rounded-b-lg">
        <div class="px-10 pt-4 pb-8">
            <h1>Edit prize</h1>
            <form method="POST" action="{{ route('backstage.prizes.store') }}" enctype="multipart/form-data">
                @include('backstage.prizes.form')
            </form>
        </div>
    </div>
@endsection

resources/views/backstage/prizes/form.blade.php
@csrf

@include('backstage.partials.forms.text', [
    'field' => 'title',
    'label' => 'Title',
    'value' => old('title') ?? $prize->title,
])

@include('backstage.partials.forms.text', [
    'field' => 'description',
    'label' => 'Description',
    'value' => old('description') ?? $prize->description,
])

@include('backstage.partials.forms.number', [
    'field' => 'weight',
    'label' => 'Weight',
    'step' => 1,
    'value' => old('weight') ?? $prize->weight,
])


@include('backstage.partials.forms.starts-ends', [
    'starts_at' => old('starts_at') ?? ($prize->starts_at === null ? $prize->starts_at : $prize->starts_at->format('d-m-Y H:i:s')),
    'ends_at' => old('ends_at') ?? ($prize->ends_at === null ? $prize->ends_at : $prize->ends_at->format('d-m-Y H:i:s')),
    'minDate' => $activeCampaign->starts_at,
    'maxDate' => $activeCampaign->ends_at,
])


@includeWhen(empty($disabled), 'backstage.partials.forms.submit')

resources/views/backstage/prizes/index.blade.php
@extends('templates.backstage')

@section('tools')


    <a href="{{ route('backstage.prizes.create') }}" class="button-create">Create prize</a>

@endsection

@section('content')
    <div id="card" class="bg-white shadow-lg mx-auto rounded-b-lg">
        <div class="px-10 pt-4 pb-8">
            @livewire('backstage.prizes-table')
        </div>
    </div>
@endsection

resources/views/backstage/prizes/show.blade.php
@extends('templates.backstage')

@section('tools')

    @if( auth()->user()->isAdmin() )
    <a href="{{ route('backstage.prizes.create') }}" class="button-create">Create prize</a>
    <a href="{{ route('backstage.prizes.edit', $prize->customerlevel_id) }}" class="button-create">Edit prize</a>
    @endif
@endsection

@section('content')
    <div id="card" class="bg-white shadow-lg mx-auto rounded-b-lg">
        <div class="px-10 pt-4 pb-8">
            @include('backstage.partials.views.text', [
                'label' => 'Customer Level',
                'value' => $prize->customerlevel->name,
            ])

            @include('backstage.partials.views.text', [
                'label' => 'Redirect URL desktop',
                'value' => $prize->redirect_desktop,
            ])

            @include('backstage.partials.views.text', [
                'label' => 'Redirect URL mobile',
                'value' => $prize->redirect_mobile,
            ])

            @includeWhen($activeCampaign->segmentation, 'backstage.partials.forms.select', [
                'label' => 'Customer Segment',
                'value' =>  $prize->customer_segmentation->name ?? '',
            ])

            @if( $prize->prizes->count() > 0)
                <div class="grid grid-cols-5 gap-4 items-start py-2 border-b border-gray-100 mt-5">
                    <div class="col-span-1 font-semibold">Prize Type</div>
                    <div class="col-span-1 font-semibold">Prize Amount</div>
                    <div class="col-span-1 font-semibold">Image Popup</div>
                    <div class="col-span-1 font-semibold">Points Band</div>
                    <div class="col-span-1 font-semibold">Message</div>
                </div>
                @foreach ($prize->prizes as $value)
                    <div class="grid grid-cols-5 gap-4 items-start py-2 border-b border-gray-100">
                        <div class="col-span-1">{{ $prize::$prizetype[$value->prize_type]}}</div>
                        <div class="col-span-1">{{ $value->prizeamount}}</div>
                        <div class="col-span-1"><img src="{{env('DO_CDN_URL'). $value->popup_image }}" class="img-responsive w-16"  /> </div>
                        <div class="col-span-1">{{ $value->getPointsBand($value->points_band)}}</div>
                        <div class="col-span-1">{{ $value->message }}</div>
                    </div>
                @endforeach
            @endif
        </div>
    </div>
@endsection